### ISSUE TITLE
local editors in a repo without an initial commit -> NPE

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-resolver#12]
I created a new rug archive (with AddRugArchiveProject generator), ran `git init` but did not make an initial commit, created an editor and tried to run it:

```
$ rug edit -lRC ~/code/atomist-workspace/atomist-rugs/rug-editors/ AddReadme -X

java.lang.NullPointerException
	at com.atomist.rug.git.RepositoryDetailsProvider.readDetails(RepositoryDetailsProvider.java:29)
	at com.atomist.project.ProvenanceInfoArtifactSourceReader.read(ProvenanceInfoArtifactSourceReader.java:84)
	at com.atomist.rug.manifest.ManifestReader.read(ManifestReader.java:70)
...
```

**Comment by cdupuis** [comment]
Fixed in c46535d0a24e9dbfa5c50e5a1b57eccb4adba848
