### ISSUE TITLE
Can't test a generator that doesn't have a project_name argument

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-resolver#17]
```
java.lang.UnsupportedOperationException
	at scala.collection.convert.Wrappers$IteratorWrapper.remove(Wrappers.scala:34)
	at scala.collection.convert.Wrappers$IteratorWrapper.remove(Wrappers.scala:29)
	at java.util.AbstractCollection.remove(AbstractCollection.java:293)
	at com.atomist.rug.loader.DecoratingOperationsLoader$DecoratedProjectGenerator.generate(DecoratingOperationsLoader.java:349)
	at com.atomist.rug.test.TestRunner.com$atomist$rug$test$TestRunner$$executeGenerator(TestRunner.scala:166)
	at com.atomist.rug.test.TestRunner$$anonfun$1.apply(TestRunner.scala:78)
	at com.atomist.rug.test.TestRunner$$anonfun$1.apply(TestRunner.scala:69)
```
...

**Comment by cdupuis** [comment]
What version of the rug-cli are you using? I can't re-create this with latest 0.23.0
